### ISSUE TITLE
Error when arming and disarming

### ISSUE THREAD

**Issue by M1gul1t0** [guerrerotook/securitas-direct-new-api#205] opened 2024-02-12 22:19 UTC
Hello, I have updated the integration to the latest version, when I try to arm or disarm the integration from homeassistant an error occurs.

The alarm_control_panel/alarm_disarm service could not be called. 'ApiManager' object has no attribute 'protom_response'

Does anybody know what is it due to?

sorry for my english but i don't know how to speak it

**Comment by TheGui01** [comment] 2024-02-13 06:22
Hello,

I have the same issue here with v2.7.1.
I had to delete the app to be able to rollback propoerly on 2.7

Rgds,
Guillaume

**Comment by cantupaz** [comment] 2024-02-14 04:45
I found a bug that may be the cause of this, but to be sure: Does this happen all the time?

**Comment by Nodezero1** [comment] 2024-02-14 06:20
Hello, For me I was having the same response every time I tried to arm the alarm and rolled back to the previous version.  Just to add, I am using Verisure France.

**Comment by Osconse** [comment] 2024-02-15 07:06
I have the same problem and error since the last update.

**Comment by rencmbr** [comment] 2024-02-15 16:31
Same problem since the update to version 2.7.1.0. 
I am using Verisure Brazil.

**Comment by petarlaf** [comment] 2024-02-16 07:16
Same issue since last release. Both for arming and disarming.

"HomeAssistantError: 'ApiManager' object has no attribute 'protom_response'"

**Comment by garybrowngeo** [comment] 2024-02-16 09:15
Same issue. Reverted to previous version (2.7.0.0) and problem no longer occurs.

**Comment by samatild** [comment] 2024-02-19 21:04
+1 
rolled back to 2.7.0.0 and the issue is gone

**Comment by cantupaz** [comment] 2024-02-23 09:34
Closing. Fixed in 2.7.2. please reopen if needed.

**Closed by cantupaz** 2024-02-23 09:34 UTC
